// 关系边：充分 / 必要 / 充要 / 无关
// type: iff=充要(A⇔B)  suff=充分不必要(A⇒B)  need=必要不充分(B⇒A)  none=既不充分也不必要  rel=概念关联
const EDGE_LIST = [
  // ---------- 行列式内部 ----------
  ['det-triangular', 'det-elimination', 'rel', '同一个求值动作的两面：化三角形是过程，对角线之积是终点公式（并非两个命题互为条件）'],
  ['det-elimination', 'det-def', 'suff', '化三角形是定义式计算的替代路径'],
  ['det-expansion', 'det-triangular', 'suff', '展开→降阶'],
  ['det-cofactor', 'det-expansion', 'need', '余子式是展开定理的必备构件'],
  ['det-add-row', 'det-elimination', 'need', '化三角的合法性来自倍加不变性'],
  ['det-swap', 'det-elimination', 'rel', '换行是化三角形的三种基本手段之一（换行、倍乘、倍加），但不是唯一手段'],
  ['det-multilinearity', 'det-def', 'none', '性质可加速计算，但非定义所需'],
  ['det-swap', 'det-rowsum-zero', 'suff', '两行相同⇒｜A｜=0'],
  ['det-rowsum-zero', 'mat-invertible-crit', 'iff', '｜A｜=0 与不可逆一一对应'],
  ['det-rank', 'mat-rank', 'iff', '子式判定与秩的定义同源'],
  ['det-rank', 'mat-invertible-crit', 'iff', '满秩 ⇔ 可逆'],
  ['det-product', 'mat-invertible-crit', 'suff', '｜A｜｜B｜≠0 ⇒ AB 可逆'],
  ['det-vandermonde', 'det-elimination', 'suff', '识别为范德蒙德即得结果'],
  ['det-arrow', 'det-elimination', 'suff', '爪形化为三角'],
  ['det-roots', 'det-rowsum-zero', 'suff', '令行列式为零即判相关'],
  ['det-block', 'det-triangular', 'suff', '分块三角退化即三角行列式'],
  ['det-def', 'det-transpose', 'rel', '定义式按行按列对称'],

  // ---------- 行列式 → 矩阵/向量/方程组 ----------
  ['mat-invertible-crit', 'mat-inverse-def', 'iff', '可逆即存在逆矩阵'],
  ['mat-adj-identity', 'mat-inv-method', 'need', '伴随公式法求逆的依据'],
  ['mat-adjoint', 'mat-adj-identity', 'need', '先有 A* 才有该恒等式'],
  ['mat-adj-rank', 'det-rank', 'need', '需借助行列式为零判定降秩'],
  ['mat-adj-rank', 'mat-invertible-crit', 'suff', 'r(A)=n ⇒ A* 可逆'],
  ['mat-mult', 'mat-power', 'need', '矩阵幂就是同一个矩阵反复相乘'],
  ['mat-noncommute', 'mat-power', 'suff', '不可交换 ⇒ (A+B)² 不能套二项式'],
  ['mat-nocancel', 'mat-nocancel-2', 'suff', '无零因子与无消去律同根同源'],
  ['mat-invertible-crit', 'mat-nocancel-2', 'iff', '可逆 ⇔ 可以消去'],
  ['mat-invertible-crit', 'mat-nocancel', 'iff', '不可逆 ⇔ 必有非零零因子'],
  ['mat-transpose', 'mat-orthogonal', 'need', '正交性用转置定义'],
  ['mat-orthogonal', 'mat-invertible-crit', 'suff', '正交矩阵必可逆'],
  ['mat-trace', 'eig-poly', 'need', 'tr = Σλ 需特征值信息'],

  // ---------- 矩阵内部 ----------
  ['mat-linear', 'mat-mult', 'need', '先有加法数乘才有完整运算体系'],
  ['mat-elem-op', 'mat-rank-invariance', 'iff', '初等变换保秩正是这条不变性的内容本身：等价变换的定义就是秩不变'],
  ['mat-elem-op', 'mat-equiv', 'iff', '等价就是用有限次初等变换相互转化'],
  ['mat-elem-mat', 'mat-elem-op', 'iff', '初等矩阵与初等变换一一对应'],
  ['mat-elem-relation', 'mat-elem-mat', 'need', '先认清"左乘 E 就是作一次行变换"，才能用行变换把 A 化成等价标准形'],
  ['mat-elem-relation', 'det-product', 'need', '由 ｜AB｜=｜A｜｜B｜ 推出变换对行列式的影响'],
  ['mat-elem-mat', 'mat-inv-method', 'suff', '初等矩阵之积 ⇒ 可用 (A|I) 求逆'],
  ['mat-equiv', 'mat-rank', 'iff', '同型矩阵等价 ⇔ 秩相等'],
  ['mat-equiv', 'mat-invertible-crit', 'suff', 'A 等价于 I ⇒ A 可逆'],
  ['mat-block', 'det-block', 'need', '分块行列式以分块矩阵为对象'],
  ['mat-rank-invariance', 'mat-rank', 'need', '不变性建立在秩的定义之上'],
  ['mat-rank-ineq', 'mat-rank', 'need', '不等式的对象是秩'],
  ['mat-rank-crit', 'mat-rank', 'need', '判定以秩的取值为依据'],
  ['mat-rank-crit', 'mat-adj-rank', 'iff', '两种语言描述同一分段结论'],
  ['mat-def', 'mat-types', 'rel', '特殊矩阵是矩阵的特例'],
  ['mat-elem-op', 'eq-gauss', 'suff', '初等行变换是消元法的操作'],

  // ---------- 向量与线性相关性 ----------
  ['vec-combo', 'vec-indep-def', 'need', '相关性用线性组合是否为零定义'],
  ['vec-indep-def', 'vec-indep-crit', 'need', '判定方法服务于定义'],
  ['vec-indep-def', 'vec-indep-concl', 'need', '结论由定义推出'],
  ['vec-indep-crit', 'det-rowsum-zero', 'suff', '方阵时判定归于 ｜A｜ 是否为 0'],
  ['vec-indep-crit', 'mat-rank', 'suff', '一般情形判定归于秩与向量个数是否相等'],
  ['vec-rank-def', 'vec-maximal', 'iff', '秩即极大无关组所含向量个数'],
  ['vec-maximal', 'vec-equivalent', 'suff', '极大无关组与原组等价'],
  ['vec-equivalent', 'vec-rank-def', 'suff', '等价 ⇒ 秩相等（反之不然）'],
  ['vec-rank-vs-mat', 'mat-rank', 'iff', '行秩＝列秩＝矩阵的秩'],
  ['vec-rank-vs-mat', 'vec-rank-def', 'iff', '同一秩的两种表述'],
  ['vec-express-crit', 'vec-combo', 'need', '能否表示是线性表示的核心问题'],
  ['vec-rank-table', 'vec-express-crit', 'suff', '以少表多必相关'],
  ['vec-inner', 'vec-schmidt', 'need', '正交化以内积为工具'],
  ['vec-schmidt', 'eig-orth-diag', 'suff', '正交化是正交对角化的必备步骤'],
  ['vec-def', 'vec-inner', 'rel', '内积是向量的运算'],
  ['vec-indep-def', 'mat-invertible-crit', 'iff', '列组无关 ⇔ 矩阵可逆'],

  // ---------- 方程组 ----------
  ['eq-gauss', 'eq-homo-sol', 'suff', '消元即可判齐次解的情形'],
  ['eq-gauss', 'eq-homo-structure', 'suff', '自由未知量个数给出基础解系规模'],
  ['eq-homo-sol', 'eq-homo-structure', 'need', '有非零解才谈基础解系'],
  ['eq-homo-sol', 'eq-homo-general', 'need', '通解以基础解系为构件'],
  ['eq-homo-structure', 'eq-homo-general', 'suff', '基础解系的线性组合即通解'],
  ['eq-gauss', 'eq-nonhomo-crit', 'suff', '化行最简形后比较两个秩'],
  ['eq-nonhomo-crit', 'eq-rank-relation', 'need', '相容性判别用系数与增广矩阵的秩'],
  ['eq-nonhomo-crit', 'eq-nonhomo-general', 'need', '先判有解再写通解'],
  ['eq-homo-general', 'eq-nonhomo-general', 'need', '非齐次通解＝特解＋齐次通解'],
  ['eq-homo-nonhomo', 'eq-homo-sol', 'need', '讨论基于齐次的解集情形'],
  ['eq-homo-nonhomo', 'eq-nonhomo-crit', 'need', '还需相容性判别'],
  ['eq-cramer', 'eq-nonhomo-crit', 'suff', '｜A｜≠0 ⇒ 唯一解'],
  ['eq-cramer', 'eq-homo-sol', 'suff', '｜A｜≠0 ⇒ 齐次只有零解'],
  ['eq-cramer', 'det-product', 'need', '公式的分子分母都是行列式'],
  ['eq-AX-O-AB-O', 'eq-homo-sol', 'iff', 'AB=O 即 B 的列都是齐次解'],
  ['eq-samesol', 'eq-homo-general', 'need', '同解判定需比较解集'],
  ['eq-samesol', 'vec-equivalent', 'iff', '同解 ⇔ 行向量组可相互线性表示'],
  ['eq-geometry', 'eq-nonhomo-crit', 'need', '几何形态由秩决定'],
  ['eq-nonhomo-general', 'mat-inv-method', 'need', '矩阵方程求解常用逆矩阵'],
  ['eq-gauss', 'mat-adj-rank', 'suff', '解方程组可求伴随矩阵的秩'],

  // ---------- 特征值 ----------
  ['eig-def', 'eig-poly', 'need', '特征方程由定义式导出'],
  ['eig-poly', 'eig-vector-space', 'need', '先求 λ 再求特征向量'],
  ['eig-vector-space', 'eq-homo-general', 'suff', '特征向量就是齐次方程组的非零解'],
  ['eig-vector-space', 'eig-mult', 'suff', '解空间维数即几何重数'],
  ['eig-mult', 'eig-property', 'suff', '几何重数≤代数重数 ⇒ 特征向量不够则不可对角化'],
  ['eig-property', 'eig-diag-crit', 'need', '判定对角化需数线性无关特征向量的个数'],
  ['eig-mult', 'eig-diag-crit', 'iff', '几何重数＝代数重数 ⇔ 可对角化'],
  ['eig-diag-crit', 'eig-diag-method', 'need', '先判可对角化再作对角化'],
  ['eig-diag-method', 'eig-power-app', 'suff', '对角化后立得幂与矩阵函数'],
  ['eig-similar', 'eig-similar-prop', 'need', '性质由相似定义推出'],
  ['eig-similar-prop', 'eig-similar-crit', 'suff', '不变量不同即可判不相似'],
  ['eig-similar', 'eig-diag-crit', 'suff', 'A 相似于对角阵 ⇔ A 可对角化'],
  ['eig-ops', 'eig-trace-det-app', 'suff', '代入法即得 ｜A+kI｜ 与 A* 的特征值'],
  ['eig-ops', 'mat-adj-rank', 'suff', 'A* 的特征值 ｜A｜/λ 可反推可逆性'],
  ['eig-ops', 'mat-trace', 'need', 'tr＝Σλ 是性质的一部分'],
  ['eig-symmetric', 'eig-orth-diag', 'iff', '实对称矩阵必可正交对角化，反之亦然'],
  ['eig-orth-diag', 'qf-orthogonal', 'rel', '正交对角化 QᵀAQ＝Λ 正是正交变换法化标准形的内核：同一件事的两种说法'],
  ['eig-diag-method', 'sp-similar-transform', 'rel', '对角化是换基观点的特例'],
  ['eig-similar-crit', 'mat-trace', 'suff', '迹不同即可判不相似'],
  ['eig-symmetric', 'eig-similar-prop', 'suff', '特征值相同 ⇒ 实对称矩阵相似'],
  ['eig-minpoly', 'eig-diag-crit', 'iff', '最小多项式无重根 ⇔ 可对角化'],
  ['eig-def', 'mat-invertible-crit', 'iff', 'A 可逆 ⇔ 特征值全非零'],
  ['eig-estimate', 'eig-def', 'suff', '圆盘定理用于估计特征值位置'],

  // ---------- 二次型 ----------
  ['qf-def', 'eig-def', 'need', '二次型的矩阵是实对称矩阵，其性质依赖特征值'],
  ['qf-def', 'qf-canonical', 'need', '化标准形以二次型为对象'],
  ['qf-complete-square', 'qf-canonical', 'suff', '配方法给出标准形'],
  ['qf-orthogonal', 'qf-canonical', 'suff', '正交变换法给出标准形'],
  ['qf-orthogonal', 'eig-orth-diag', 'rel', '正交变换法就是正交对角化的算法外壳：f＝xᵀAx 令 x＝Qy 即得 QᵀAQ＝Λ，标准形系数就是特征值'],
  ['qf-canonical', 'qf-inertia-index', 'need', '惯性指数由标准形平方项符号统计'],
  ['qf-inertia-index', 'qf-inertia-law', 'iff', '惯性指数不变 ⇔ 规范形唯一'],
  ['qf-inertia-law', 'qf-congruent', 'iff', '实对称矩阵合同 ⇔ 惯性指数分别相同'],
  ['qf-congruent', 'eig-similar', 'none', '合同（CᵀAC）与相似（P⁻¹AP）互不充分'],
  ['qf-contract-vs-similar', 'qf-congruent', 'need', '对比以合同为一方'],
  ['qf-contract-vs-similar', 'eig-similar', 'need', '对比以相似为另一方'],
  ['qf-congruent', 'mat-orthogonal', 'suff', '取 C 为正交矩阵时 CᵀAC＝C⁻¹AC，同一个变换同时实现合同与相似（逆向不成立）'],
  ['qf-positive-def', 'qf-canonical', 'need', '正定性用标准形符号刻画'],
  ['qf-orthogonal', 'qf-rayleigh', 'need', '把分母 xᵀx 抹平要靠正交变换：标准形的系数就是特征值，加权平均才写得出来'],
  ['qf-canonical', 'qf-rayleigh', 'need', '标准形的系数就是特征值，瑞利商的两个端点直接由标准形读出'],
  ['qf-rayleigh', 'qf-positive-crit', 'iff', '瑞利商恒大于零 ⇔ 最小特征值大于零 ⇔ A 正定'],
  ['qf-rayleigh', 'eig-estimate', 'rel', '同一条不等式的两种用法：瑞利商给二次型的值域，估计给特征值的范围'],
  ['qf-positive-def', 'qf-positive-crit', 'need', '充要条件是判定的展开'],
  ['qf-positive-crit', 'qf-inertia-index', 'iff', '正定 ⇔ p＝n'],
  ['qf-positive-crit', 'eig-symmetric', 'iff', '正定 ⇔ 特征值全为正'],
  ['qf-positive-crit', 'qf-semi-def', 'need', '半正定判据由正定放宽得到'],
  ['qf-semi-def', 'mat-rank', 'suff', '半正定时 r(A) 等于正特征值个数'],
  ['qf-inertia-index', 'mat-rank', 'suff', '正负惯性指数之和 p+q 就是二次型的秩 r(A)：会算惯性指数就能读出秩（反之不成立）'],
  ['qf-def', 'mat-types', 'suff', '二次型矩阵必为对称矩阵'],
  ['qf-contract-vs-similar', 'mat-equiv', 'suff', '合同与相似都强于等价'],

  // ---------- 线性空间与线性变换 ----------
  ['sp-def', 'sp-dim-basis', 'need', '先有空间才谈基与维数'],
  ['sp-dim-basis', 'sp-transition', 'need', '过渡矩阵连接两组基'],
  ['sp-transition', 'sp-similar-transform', 'suff', '换基导致矩阵相似'],
  ['sp-transform', 'sp-similar-transform', 'iff', '变换与矩阵在取定基下一一对应'],
  ['sp-similar-transform', 'eig-similar', 'iff', '相似即同一变换在不同基下的矩阵'],
  ['sp-transform', 'sp-kernel-image', 'need', '核与像是变换的子空间'],
  ['sp-kernel-image', 'eq-homo-general', 'suff', '核即齐次方程组的解空间'],
  ['sp-dim-basis', 'vec-rank-def', 'rel', '维数是基所含向量个数'],
  ['sp-def', 'vec-inner', 'suff', '内积空间是线性空间的加强'],
  ['sp-similar-transform', 'qf-congruent', 'suff', '同一变换 + 正交基 ⇒ 正交合同'],

  // ---------- 跨章枢纽 ----------
  ['mat-invertible-crit', 'eig-diag-crit', 'suff', '可逆 + 可对角化 ⇒ 对角元非零'],
  ['mat-invertible-crit', 'eq-homo-sol', 'iff', '可逆 ⇔ 齐次只有零解'],
  ['mat-invertible-crit', 'vec-indep-def', 'iff', '可逆 ⇔ 列组线性无关'],
  ['mat-invertible-crit', 'det-rowsum-zero', 'iff', '可逆 ⇔ ｜A｜≠0'],
  ['mat-invertible-crit', 'mat-rank', 'iff', '可逆 ⇔ 满秩'],
  ['mat-rank', 'eq-rank-relation', 'need', '相容性判别以秩为语言'],
  ['mat-rank-ineq', 'eq-AX-O-AB-O', 'suff', '乘法秩不等式 r(AB) ≥ r(A)+r(B)−n 中令 r(AB)=0，即得 AB=O 时的 r(A)+r(B) ≤ n（特例，反过来不成立）'],
  ['det-def', 'eig-poly', 'suff', '特征多项式是行列式'],
  ['det-product', 'eig-trace-det-app', 'suff', '｜A｜＝∏λ 由乘积公式与相似不变性得到'],
  ['mat-trace', 'eig-trace-det-app', 'suff', 'tr＝Σλ 提供反解参数的另一方程'],
  ['vec-indep-crit', 'eig-property', 'suff', '不同特征值的特征向量线性无关'],
  ['vec-rank-table', 'eig-mult', 'suff', '以少表多必相关 ⇒ 几何重数受限'],

  // ---------- 补边：矩阵运算基础（第二章前段）接入主体 ----------
  // 把这 5 个点（矩阵加法数乘、矩阵乘法、方阵的幂、AB≠BA、用初等变换解 AX=B）接回全书主干
  ['mat-mult', 'mat-eq-solve', 'need', 'AX = B 本身就是一个矩阵乘法等式，"解矩阵方程"就是解这个乘法等式'],
  ['mat-mult', 'mat-inv-method', 'need', '求逆的三条路都要求会算 AB：伴随式用到 AA*，定义法要凑 AB = E'],
  ['mat-mult', 'mat-invertible-crit', 'need', 'AB = BA = E 中的乘法就是矩阵乘法，离开它无法陈述可逆'],
  ['mat-mult', 'mat-elem-op', 'rel', '左乘初等矩阵＝作一次行变换、右乘＝作一次列变换 —— 初等变换与矩阵乘法在这里一一对应（初等变换本身不需要乘法就能定义，故为关联而非必要条件）'],
  ['mat-linear', 'mat-rank', 'need', '秩的加法不等式 r(A+B) ≤ r(A)+r(B) 以矩阵加法为前提，是秩的基本性质'],
  ['mat-power', 'eig-power-app', 'rel', '同一个"求 Aᵏ"主题的两种手段：初等技巧（拆分/秩 1）与对角化'],
  ['mat-power', 'eig-diag-method', 'rel', '求 Aᵏ 的两条主线之一：对角化 A = PΛP⁻¹ ⇒ Aᵏ = PΛᵏP⁻¹'],
  ['mat-power', 'eig-trace-det-app', 'rel', '秩 1 矩阵的幂公式 Aᵏ = (trA)^{k−1}A 要用迹，与"用特征值求幂"同属一套应用'],
  ['mat-noncommute', 'mat-invertible-crit', 'rel', '乘法不交换使消去律失效，可逆正是把它救回来的条件'],
  ['mat-noncommute', 'mat-nocancel', 'rel', '乘法不交换是有零因子、无消去律这些反直觉现象的同一个根源'],
  ['mat-noncommute', 'eig-property', 'rel', '可交换与"特征向量共享"是同一件事的两面：AB = BA 时 B 把 A 的每个特征子空间映到自身，λ 是单根时就是公共特征向量（可同时对角化）'],
  ['mat-elem-op', 'mat-eq-solve', 'need', '(A | E) → (E | A⁻¹)、(A|B) → (E|A⁻¹B) 靠的正是三种初等行变换'],
  ['mat-eq-solve', 'mat-inv-method', 'rel', '(A|B) 的行化简就是 (A|E) 求逆的加宽版：得到 E 即得 A⁻¹，同步读出 X'],
  ['mat-eq-solve', 'eq-AX-O-AB-O', 'suff', '把 B 换成 O 即得齐次矩阵方程 AX = O，解法与 AX = B 完全同形'],
  ['det-expansion', 'det-tridiagonal', 'need', '三对角行列式靠按第一行展开建立递推 Dₙ＝aDₙ₋₁−bcDₙ₋₂（反之不成立）'],
  ['qf-positive-def', 'mat-orthogonal', 'suff', '正定矩阵与 E 合同，而 E 本身正交；正定矩阵又是实对称的，必可正交对角化（反之不成立）'],
];
