const EQ = [];
// 续：第四章 线性方程组（基础，全部要求）
EQ.push({ id: 'm-eq', title: '第四章 线性方程组', x: 200, y: -960, summary: '基础/数一/数二 均要求（数二核心考点）。核心：解的存在性判别、基础解系与通解结构。', points: [
  { id: 'eq-homo-sol', title: '齐次方程组 Ax = 0', module: 'm-eq', tags: ['基础'], summary: '必有零解；有非零解 ⇔ r(A) < n ⇔ 列组线性相关 ⇔ ｜A｜=0（方阵）。',
    note: '齐次方程组永远相容，问题只在于"只有零解"还是"有无穷多解"。',
    prop: ['Ax=0 有非零解 ⇔ r(A) < n', 'n 个未知数、n 个方程时有非零解 ⇔ ｜A｜=0'],
    pitfalls: ['把"有非零解"的条件写成 r(A) ≤ n 之外的形式'] },
  { id: 'eq-homo-structure', title: '基础解系', module: 'm-eq', tags: ['基础'], summary: 'Ax=0 的解向量组的极大无关组；当 r(A)=r<n 时含 n−r 个向量 ξ₁,…,ξ_{n−r}。',
    note: '基础解系不唯一，但向量个数恒为 n−r(A)。',
    prop: ['基础解系含 n − r(A) 个解向量', '任一解可唯一由基础解系线性表示'],
    pitfalls: ['把自由未知量取值的组数当成解的个数（应是 n−r）'] },
  { id: 'eq-homo-general', title: '齐次方程组的通解与解空间', module: 'm-eq', tags: ['基础'], summary: 'x = k₁ξ₁ + … + k_{n−r}ξ_{n−r}（kᵢ 任意）；所有解构成 n−r 维子空间（解空间）。',
    note: '解空间维数 dim N(A) = n − r(A)，即"零度"，与秩定理对应。',
    prop: ['解集 = 基础解系的全部线性组合', 'dim N(A) + r(A) = n'],
    pitfalls: ['通解中漏写任意常数 kᵢ'] },
  { id: 'eq-nonhomo-crit', title: '非齐次方程组 Ax = b 的相容性判别', module: 'm-eq', tags: ['基础'], summary: '有解 ⇔ r(A) = r(A,b)；无解 ⇔ r(A) < r(A,b)（此时 r(A)+1 = r(A,b)）。',
    note: '判别只比较两个秩，特别地 r(A,b) 最多比 r(A) 大 1。',
    prop: ['r(A)=r(A,b)=n ⇒ 唯一解', 'r(A)=r(A,b)<n ⇒ 无穷多解'],
    pitfalls: ['只比较 r(A) 与 n 而漏掉增广矩阵的秩'] },
  { id: 'eq-nonhomo-general', title: '非齐次方程组的通解结构', module: 'm-eq', tags: ['基础'], summary: '通解 = 特解 η* + 对应齐次方程组的通解；任意两解之差是对应齐次的解。',
    note: '结构定理：解集是"仿射集"，不是子空间（除非 b=0）。',
    prop: ['x = η* + k₁ξ₁ + … + k_{n−r}ξ_{n−r}', 'η₁,η₂ 为解 ⇒ η₁−η₂ 是 Ax=0 的解'],
    pitfalls: ['把非齐次通解写成纯齐次形式，丢掉特解'] },
  { id: 'eq-rank-relation', title: '系数矩阵与增广矩阵的关系', module: 'm-eq', tags: ['基础'], summary: 'r(A) ≤ r(A,b) ≤ r(A)+1；两者相等 ⇔ 有解，相差 1 ⇔ 无解。',
    note: '再结合 r(A) ≤ min{m,n} 与 n 的关系即可一次性判完所有情形。',
    prop: ['r(A) ≤ r(A,b) ≤ r(A)+1', 'r(A,b)=r(A) ⇔ b 可由 A 的列组线性表示'],
    pitfalls: ['忘记 r(A,b) 至多比 r(A) 大 1 这一上限'] },
  { id: 'eq-cramer', title: '克拉默法则', module: 'm-eq', tags: ['基础'], summary: 'n 个方程 n 个未知数且 ｜A｜≠0 时，xⱼ = ｜Aⱼ｜/｜A｜（Aⱼ 为第 j 列换成 b）。',
    note: '仅适用于"方程数 = 未知数个数且系数行列式非零"的窄场景。',
    prop: ['｜A｜≠0 ⇒ 解存在且唯一', '齐次情形 ｜A｜≠0 ⇒ 只有零解'],
    pitfalls: ['方程数与未知数个数不等时套用克拉默法则'] },
  { id: 'eq-homo-nonhomo', title: '齐次与非齐次解的关系', module: 'm-eq', tags: ['基础'], summary: 'Ax=0 只有零解 ⇒ Ax=b 解唯一（若有解）；Ax=0 有非零解 ⇒ Ax=b 若有解则有无穷多解。',
    note: '两套情形组合成四种可能：无解 / 唯一解 / 无穷多解 / 只有零解。',
    prop: ['无解与唯一解不可能同时出现', '无穷多解 ⇔ 有解且 r(A)<n'],
    pitfalls: ['把"齐次只有零解"当成"非齐次一定有解"'] },
  { id: 'eq-samesol', title: '同解方程组与公共解', module: 'm-eq', tags: ['数一'], summary: '两个方程组同解 ⇔ 解集相同；求公共解可联立求解，或用一组的通解代入另一组。',
    note: '同解判定常用：r(A)=r(B) 且 B 的行可由 A 的行线性表示（反之亦然）。',
    prop: ['Ax=0 与 Bx=0 同解 ⇒ r(A)=r(B)', '公共解：联立两组方程求通解'],
    pitfalls: ['仅由 r(A)=r(B) 断言同解'] },
  { id: 'eq-AX-O-AB-O', title: '矩阵方程 AX = O 与 AB = O', module: 'm-eq', tags: ['数一'], summary: 'AB = O ⇔ B 的每一列都是 Ax=0 的解 ⇒ r(A)+r(B) ≤ n（A 为 m×n）。',
    note: '这是把矩阵等式翻译成方程组语言、进而用秩证明的经典转换。',
    prop: ['AB=O ⇒ r(A)+r(B) ≤ n', 'B 的列向量都落在 A 的零空间中'],
    pitfalls: ['用错 n：应为 A 的列数、也就是 B 的行数'] },
  { id: 'eq-gauss', title: '高斯消元法与行阶梯形', module: 'm-eq', tags: ['基础'], summary: '对增广矩阵作初等行变换化为行最简形，选出主元，把自由未知量取为参数写出通解。',
    note: '求秩、求基础解系、求通解、求极大无关组的统一操作平台。',
    prop: ['主元个数 = r(A)', '自由未知量个数 = n − r(A)'],
    pitfalls: ['对增广矩阵作列变换（会改变解集）'] },
  { id: 'eq-geometry', title: '方程组的几何意义（平面与直线）', module: 'm-eq', tags: ['基础'], summary: '三个未知数时，每个方程表示一张平面；解的情况对应三平面的相交形态（一点、一条线、无公共点等）。',
    note: '用秩的语言统一描述几何位置关系，是选择题的形象化背景。',
    prop: ['唯一解 ⇔ 三平面交于一点', '无穷多解 ⇔ 交于一条直线或重合'],
    pitfalls: ['只凭图形直觉判断，忽略秩这一严格判据'] },
] });
