const MX = [];
// 续：第二章 矩阵（基础，全部要求）
MX.push({ id: 'm-mat', title: '第二章 矩阵', x: -1800, y: -120, summary: '基础/数一/数二 均要求。核心：矩阵乘法、逆矩阵与伴随矩阵、初等变换与秩，是线代全书的运算主干。', points: [
  { id: 'mat-def', title: '矩阵的定义与相等', module: 'm-mat', tags: ['基础'], summary: 'm×n 个数排成的数表 A=(aᵢⱼ)；同型且对应元素全相等才相等。',
    note: '矩阵与行列式本质不同：矩阵是数表（可加减、不可"算成一个数"），行列式是一个数。',
    prop: ['只有同型矩阵才能谈相等、加减'], pitfalls: ['把"矩阵相等"与"行列式相等"混为一谈'] },
  { id: 'mat-types', title: '常见特殊矩阵', module: 'm-mat', tags: ['基础'], summary: '零矩阵、单位矩阵、对角矩阵、数量矩阵、三角矩阵、对称与反对称矩阵。',
    note: '对称：Aᵀ=A；反对称：Aᵀ=−A，且主对角元全为 0。',
    prop: ['kA、Aᵏ、A⁻¹、A* 仍为对角阵（对角可逆时）', 'A+Aᵀ 对称，A−Aᵀ 反对称'],
    pitfalls: ['把反对称矩阵的主对角元写成任意值（必须为 0）'] },
  { id: 'mat-linear', title: '矩阵的加法与数乘', module: 'm-mat', tags: ['基础'], summary: '同型矩阵对应元素相加；数 k 乘 A 即所有元素都乘 k。',
    note: '与行列式数乘 ｜kA｜=kⁿ｜A｜ 形成对比，是最经典的易错点。',
    prop: ['A+B = B+A', 'k(A+B) = kA+kB'], pitfalls: ['数乘与行列式数乘混淆'] },
  { id: 'mat-mult', title: '矩阵乘法', module: 'm-mat', tags: ['基础'], summary: 'A_{m×s}B_{s×n} 才有意义，结果 C_{m×n}，cᵢⱼ = Σₖ aᵢₖbₖⱼ（左行乘右列）。',
    note: '乘法无交换律、无消去律、有零因子，这三点是线代与实数运算最大的差别。',
    prop: ['要求左列数 = 右行数', '(AB)C = A(BC)；A(B+C)=AB+AC', 'r(AB) ≤ min{r(A), r(B)}'],
    pitfalls: ['先写 AB 再验证是否能乘，忽略"左列右行"'] },
  { id: 'mat-noncommute', title: 'AB ≠ BA（乘法不可交换）', module: 'm-mat', tags: ['基础'], summary: '一般 AB ≠ BA；AB = BA 称为 A 与 B 可交换，是特殊情形。',
    note: '由 (A+B)² = A²+2AB+B² 只在可交换时成立。',
    prop: ['(A+B)² = A²+AB+BA+B²', 'A 与 A*、A 与 A 的多项式可交换'],
    pitfalls: ['对 (AB)² 或 (A+B)² 直接套用二项式展开'] },
  { id: 'mat-nocancel', title: 'AB = O 没有零因子', module: 'm-mat', tags: ['基础'], summary: 'AB = O 推不出 A = O 或 B = O。',
    note: 'AB = O 的真正含义是 B 的每一列都是 Ax = 0 的解。',
    prop: ['AB=O ⇒ r(A)+r(B) ≤ n（A 为 m×n）'], pitfalls: ['由 AB=O 直接断定 A 或 B 为零矩阵'] },
  { id: 'mat-nocancel-2', title: 'AX = AY 推不出 X = Y', module: 'm-mat', tags: ['基础'], summary: '矩阵乘法不满足消去律：即使 AB = AC 也不能约去 A，除非 A 可逆。',
    note: '可逆时可消去：A 可逆且 AB = AC ⇒ B = C。',
    prop: ['A 可逆 ⇒ AB = O ⇒ B = O', 'A 可逆 ⇒ AB = AC ⇒ B = C'],
    pitfalls: ['在含未知矩阵的等式两边随意"约去"同一个矩阵'] },
  { id: 'mat-transpose', title: '矩阵的转置', module: 'm-mat', tags: ['基础'], summary: '(Aᵀ)ᵀ=A；(A+B)ᵀ=Aᵀ+Bᵀ；(kA)ᵀ=kAᵀ；(AB)ᵀ=BᵀAᵀ（要"反序"）。',
    note: '转置与求逆可自由交换：(Aᵀ)⁻¹=(A⁻¹)ᵀ。',
    prop: ['(AB)ᵀ = BᵀAᵀ', '(Aᵀ)⁻¹ = (A⁻¹)ᵀ', 'r(Aᵀ)=r(A)'],
    pitfalls: ['把 (AB)ᵀ 写成 AᵀBᵀ'] },
  { id: 'mat-power', title: '方阵的幂与矩阵多项式', module: 'm-mat', tags: ['基础'], summary: '求 Aᵏ 的常用办法：找规律、拆分 A = λE + B（B 幂零）、用秩 1 矩阵性质、用对角化。',
    note: '秩 1 矩阵 A = αβᵀ 有 Aᵏ = (βᵀα)^{k−1}A，是最高频的幂次技巧。',
    prop: ['A = λE + N，Nᵏ = O ⇒ 二项式展开只有有限项', 'A = αβᵀ ⇒ Aᵏ = (tr A)^{k−1}A'],
    pitfalls: ['对不可对角化的矩阵套用 Aᵏ = PΛᵏP⁻¹'] },
  { id: 'mat-adjoint', title: '伴随矩阵 A* 的定义', module: 'm-mat', tags: ['基础'], summary: 'A* = (Aⱼᵢ)，即把每个元素的代数余子式排成矩阵后再转置。',
    note: 'A* 的元素是代数余子式的转置排列，这是所有伴随矩阵公式的源头。',
    prop: ['A 可逆 ⇒ A* = ｜A｜A⁻¹', '二阶矩阵口诀：主对调、副变号'],
    pitfalls: ['忘记转置，把 A* 直接排成 (Aᵢⱼ)'] },
  { id: 'mat-adj-identity', title: 'AA* = A*A = ｜A｜E', module: 'm-mat', tags: ['基础'], summary: '伴随矩阵的核心恒等式：AA* = A*A = ｜A｜E。',
    note: '由此立刻得到 A⁻¹ = A*/｜A｜（｜A｜≠0）与 A* = ｜A｜A⁻¹。',
    prop: ['AA* = A*A = ｜A｜E', '｜A*｜ = ｜A｜ⁿ⁻¹'],
    pitfalls: ['把 ｜A*｜ 记成 ｜A｜ⁿ'] },
  { id: 'mat-adj-rank', title: 'A* 的秩与可逆性判定', module: 'm-mat', tags: ['基础'], summary: 'r(A*) = n（若 r(A)=n）；= 1（若 r(A)=n−1）；= 0（若 r(A)≤n−2）。',
    note: '分段结论，考试中常以"r(A)=n−1 时求 r(A*)"形式出现。',
    prop: ['r(A)=n−1 ⇒ r(A*)=1', 'r(A)≤n−2 ⇒ A*=O'],
    pitfalls: ['把 r(A)=n−1 时 A* 记成不可逆（此时 A*≠O 但不可逆）'] },
  { id: 'mat-inverse-def', title: '逆矩阵的定义', module: 'm-mat', tags: ['基础'], summary: '存在 B 使 AB = BA = E，则 B = A⁻¹ 唯一；此时称 A 可逆（非奇异）。',
    note: '逆矩阵是唯一的；只有方阵才谈逆。',
    prop: ['(A⁻¹)⁻¹ = A', '(kA)⁻¹ = k⁻¹A⁻¹ (k≠0)', '(AB)⁻¹ = B⁻¹A⁻¹'],
    pitfalls: ['把 (AB)⁻¹ 写成 A⁻¹B⁻¹'] },
  { id: 'mat-invertible-crit', title: '可逆的充要条件（汇总枢纽）', module: 'm-mat', tags: ['基础'], summary: 'A 可逆 ⇔ ｜A｜≠0 ⇔ r(A)=n ⇔ Ax=0 只有零解 ⇔ A 的行（列）组线性无关 ⇔ 特征值全非零 ⇔ A 与 E 等价 ⇔ A 可表示为初等矩阵之积。',
    note: '本知识点是全书的"枢纽节点"，几乎所有章节的结论都能挂到它下面。',
    prop: ['以上各条彼此等价，可任取一条作判据', 'A 可逆 ⇒ 行列式、秩、解、特征值四路同步变化'],
    pitfalls: ['只说"行列式不为零"，不会把它翻译成秩、解、特征值语言'] },
  { id: 'mat-inv-method', title: '逆矩阵的求法', module: 'm-mat', tags: ['基础', '数二'], summary: '(A | E) 经初等行变换化为 (E | A⁻¹)；或用伴随公式 A⁻¹ = A*/｜A｜；或定义法（凑 AB = E）。',
    note: '三阶以下常用伴随公式；求抽象矩阵的逆常用定义法与因式分解法。',
    prop: ['[A|I] ~ [I|A⁻¹] 只能做行变换', 'A² − 2A − 3E = O ⇒ 可因式分解求 A⁻¹'],
    pitfalls: ['用 (A | E) 时混入列变换导致结果错误'] },
  { id: 'mat-eq-solve', title: '用初等变换求逆与解矩阵方程 AX = B', module: 'm-mat', tags: ['基础', '数二'], summary: '对 (A | E) 作行变换得 A⁻¹；对 (A|B) 作行变换得 (E | A⁻¹B)，即 X = A⁻¹B。',
    note: '数二大纲明确要求"掌握用初等变换求矩阵的秩和逆矩阵的方法"，矩阵方程的求解就是同一手法的加宽增广块形式。',
    prop: ['(A | E) ~ (E | A⁻¹) ⇔ A 可逆', '(A|B) ~ (E | A⁻¹B) ⇒ X = A⁻¹B', 'A 不可逆时 (A|B) 化不出单位块，需改用其他方法'],
    pitfalls: ['对增广块作列变换（列变换会破坏解的结构）', '忽略 A 可逆这一前提条件'] },
  { id: 'mat-block', title: '分块矩阵及其运算', module: 'm-mat', tags: ['基础', '数二'], summary: '分块后按"小矩阵"整体做乘法、转置与求逆；分块对角阵的逆与原矩阵块的逆对应。',
    note: '分块三角阵求逆常用"待定法"或"消元法"。',
    prop: ['diag(A₁,…,Aₛ)⁻¹ = diag(A₁⁻¹,…,Aₛ⁻¹)', '(A B; C D) 可逆时可用 Schur 补'],
    pitfalls: ['分块乘法的次序与转置反序处理不当'] },
  { id: 'mat-elem-op', title: '初等变换（三种）', module: 'm-mat', tags: ['基础', '数二'], summary: '换行、乘非零数、倍加。初等行变换不改变矩阵的秩（等价变换）。',
    note: '求秩、解方程组、求逆、求极大无关组都用它。',
    prop: ['初等变换保秩', 'r(A) = 行阶梯形中非零行的行数'],
    pitfalls: ['把"初等变换"与"等价"混淆：等价是对两个矩阵说的'] },
  { id: 'mat-elem-mat', title: '初等矩阵与等价标准形', module: 'm-mat', tags: ['基础'], summary: '对 I 作一次初等变换得到初等矩阵 E；左乘 E 相当于作对应行变换，右乘相当于作列变换。',
    note: '初等矩阵都可逆，且逆仍是同类初等矩阵。',
    prop: ['E·A 实现行变换；A·E 实现列变换', 'A 可逆 ⇔ A = 初等矩阵之积'],
    pitfalls: ['分不清左乘作行变换、右乘作列变换'] },
  { id: 'mat-elem-relation', title: '初等矩阵与初等变换的对应', module: 'm-mat', tags: ['基础'], summary: '｜E｜ ≠ 0 且 ｜E(i,j)｜=−1、｜E(i(k))｜=k、｜E(ij(k))｜=1，是"初等矩阵行列式"的完整清单。',
    note: '结合 ｜AB｜=｜A｜｜B｜ 可直接推出一系列初等变换对行列式的影响。',
    prop: ['换行 → ｜E｜=−1；倍乘 → ｜E｜=k；倍加 → ｜E｜=1'],
    pitfalls: ['把倍加矩阵的行列式错记为 k'] },
  { id: 'mat-equiv', title: '矩阵等价与秩', module: 'm-mat', tags: ['基础'], summary: 'A ≅ B ⇔ 存在可逆 P,Q 使 PAQ = B ⇔ r(A) = r(B)（同型）。',
    note: '标准形：任意 m×n 矩阵 A 等价于 diag(I_r, O)，r = r(A)。',
    prop: ['等价 ⇔ 秩相等（同型）', '相似 ⇒ 等价；合同 ⇒ 等价（逆不成立）'],
    pitfalls: ['由"秩相等"得出"相似"或"合同"'] },
  { id: 'mat-rank', title: '矩阵的秩', module: 'm-mat', tags: ['基础', '数二'], summary: 'A 中非零子式的最高阶数；也等于行（列）向量组的秩，即行阶梯形非零行数。',
    note: '秩是"有效信息量"的度量：行秩 = 列秩 = 秩。',
    prop: ['0 ≤ r(A) ≤ min{m,n}', 'r(A)=n（n 阶）⇔ A 可逆'],
    pitfalls: ['把 r(A) 写成 max{m,n} 方向的不等式'] },
  { id: 'mat-rank-invariance', title: '秩的运算不变性', module: 'm-mat', tags: ['基础'], summary: 'r(A)=r(Aᵀ)=r(kA)(k≠0)=r(AᵀA)=r(AAᵀ)；可逆 P,Q 使 r(PAQ)=r(A)。',
    note: '左乘、右乘可逆矩阵（及初等变换）都不改变秩。',
    prop: ['P,Q 可逆 ⇒ r(PAQ) = r(PA) = r(AQ) = r(A)', 'r(AᵀA) = r(A)'],
    pitfalls: ['对不可逆矩阵也直接"消去"'] },
  { id: 'mat-rank-ineq', title: '秩的不等式（乘法与加法）', module: 'm-mat', tags: ['基础'], summary: 'r(A+B) ≤ r(A)+r(B)；r(AB) ≤ min{r(A),r(B)}；r(AB) ≥ r(A)+r(B)−n（A 为 m×n、B 为 n×s）。',
    note: '三条不等式是秩的证明题主力工具，配合"秩 1 分解"可解决大部分抽象秩问题。',
    prop: ['r(AB) ≥ r(A)+r(B)−n', 'AB = O ⇒ r(A)+r(B) ≤ n'],
    pitfalls: ['把 r(AB) ≥ r(A)+r(B)−n 中的 n 写成 m 或 s'] },
  { id: 'mat-rank-crit', title: '由秩判定矩阵性质', module: 'm-mat', tags: ['基础'], summary: 'r(A)=0 ⇔ A=O；n 阶方阵 r(A)=n ⇔ 可逆；r(A)=n−1 ⇒ A*≠O 且 A*不可逆。',
    note: '把秩与零矩阵、可逆、伴随矩阵秩三条判定串联起来。',
    prop: ['r(A)=n−1 ⇒ r(A*)=1', 'A≠O ⇒ r(A) ≥ 1'],
    pitfalls: ['把 r(A)=1 与 A=O 混淆'] },
  { id: 'mat-orthogonal', title: '正交矩阵与正交变换', module: 'm-mat', tags: ['数一', '数二'], summary: 'AᵀA = AAᵀ = E，即 A⁻¹ = Aᵀ；其列（行）组是标准正交基。',
    note: '正交变换保持向量长度与内积不变。数二只考正交矩阵的定义与性质，不考用它作二次型的正交变换。',
    prop: ['｜A｜ = ±1（逆不成立）', 'A,B 正交 ⇒ AB 正交', '正交矩阵的实特征值只能是 ±1'],
    pitfalls: ['误认为 ｜A｜=1 就是正交矩阵'] },
  { id: 'mat-trace', title: '矩阵的迹', module: 'm-mat', tags: ['基础', '数二'], summary: 'tr(A) = Σaᵢᵢ；tr(AB) = tr(BA)；tr(A) = Σλᵢ。',
    note: '与 ｜A｜ = ∏λᵢ 配对使用，是求特征值、参数反解的两把钥匙（数二含参特征值题几乎必用）。',
    prop: ['tr(AB) = tr(BA)', 'tr(Aᵀ)=tr(A)', '相似矩阵迹相同', 'λ₁+λ₂ = tr(A)，λ₁λ₂ = ｜A｜（二阶情形反解参数）'],
    pitfalls: ['把 tr(ABC) 与 tr(ACB) 认为一定相等（只对轮换成立）'] },
] });
